### ISSUE TITLE
It's unclear to me how it works

### ISSUE THREAD

**Issue by Eleksar387** [dustysys/ddetailer#4]
I installed it and it seems there were no errors. I select the script. And now what? How do I run it?

**Comment by boios** [comment]
Same here, I managed to get the bounding box face and the full body silhouette modes, but I can't find the way to use the head-only silhouette mode.
From the Usage Instructions: "dd-person_mask2former isolates the head's silhouette as the secondary model by using the bitwise AND option"
What does it mean? Needs clarifications

**Comment by Marc899** [comment]
How to actually use the script? Please explain

**Comment by dustysys** [comment]
First, enable previews in your settings so you can see where the masks are being placed during generation:

![image](https://user-images.githubusercontent.com/14964580/201252482-02813b29-8fa0-4005-a411-0a687cbafb70.png)
Test it out in the img2img inpaint tab first where it's easier to tell what it does. After selecting the Detection Detailer script, when you click the usual Generate button the script will run using the settings you define. Here is an example setting for auto-masking a drawn face:
![image](https://user-images.githubusercontent.com/14964580/201255266-1637fc34-c94d-49de-99b3-54e10ebe934b.png)
The highlighted region will be inpainted. Use 'Inpaint at full resolution' and 'Masked content: original' in the inpaint settings for best results.
Here is an example for masking a drawn person in full:
![image](https://user-images.githubusercontent.com/14964580/201256065-7e16fcaf-252c-41c8-b375-a2509bc0da3b.png)
Using bitwise AND(A&B) allows you to combine the mask generated from the first model selected and the second model to isolate only the face area which is detected as part of the overall person silhouette instead of the whole bounding box from the face detection model:
![image](https://user-images.githubusercontent.com/14964580/201257807-f1c066f0-8b9d-4883-81d9-990eead33da9.png)

If there are no masks drawn for a model it may be because it could not detect anything. You can try reducing the confidence threshold, or try using a different image that has a more stylized artstyle that the anime-trained models are more likely to pick up.

**Comment by boios** [comment]
Not sure if it's a bug or not but at least for me the A&B part doesn't work, I still get a box instead of a silhouette of the head. I installed the extension directly from the extension tab for what it's worth. Anyway I will try to play with the sliders and see if that change something

**Comment by dustysys** [comment]
If A lies entirely within B, A&B would be the same as A. Try expanding the size of A by using a very large dilation factor (50+) and you should see how B constrains the size of A&B.

**Comment by boios** [comment]
Yep, the dilation factor did the trick and helped me better understand what was going on. Thank you

**Comment by Eleksar387** [comment]
Thank you @dustysys for your explanation. I tried it but now getting a message in the console: No model {label_a} detections for output generation {n} with current settings.
No mask visible. I have already updated to the latest version.

**Comment by younyokel** [comment]
I just installed it on latest webUI but the script isn't visible.
![image](https://user-images.githubusercontent.com/53343081/202808698-a641c4f4-4987-4d98-9a17-b7a69cba9ba7.png)

**Comment by challengeh** [comment]
> I just installed it on latest webUI but the script isn't visible. ![image](https://user-images.githubusercontent.com/53343081/202808698-a641c4f4-4987-4d98-9a17-b7a69cba9ba7.png)

Yeah I never saw the option in the script for me either

**Comment by dustysys** [comment]
The webUI does need a full restart to install everything, and it won't work if there are any errors in the webUI terminal when you open it. Please open a new issue with any errors like that if you're still seeing the issue.

**Comment by younyokel** [comment]
> The webUI does need a full restart to install everything, and it won't work if there are any errors in the webUI terminal when you open it. Please open a new issue with any errors like that if you're still seeing the issue.

I installed the extension and put the models in mmdet folder but the Detailer option doesn't appear in img2img tab.

**Comment by kuiyanxu** [comment]
> The webUI does need a full restart to install everything, and it won't work if there are any errors in the webUI terminal when you open it. Please open a new issue with any errors like that if you're still seeing the issue.

I have restarted for many times but it didn't help!
