### ISSUE TITLE
Models?

### ISSUE THREAD

**Issue by StableInquest** [dustysys/ddetailer#5]
How can I load models from here? https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json

Thanks!

**Comment by dustysys** [comment]
To load official MMDetection pretrained models, pick one out from [this list](https://github.com/open-mmlab/mmdetection#overview-of-benchmark-and-model-zoo). 
![image](https://user-images.githubusercontent.com/14964580/201261327-a3b62419-ba8a-4db2-bb64-7730b27af84b.png)
For those labelled 'Object Detection', place them in `/models/mmdet/bbox`. For those labelled 'Instance Segmentation', place them in `/models/mmdet/segm`. 

You will need to download the model (.pth) and the config file (.py). Rename the model file to have the same name as the config file, mirroring the default ddetailer models. To download config files, click to view them and right click the 'Raw' button -> save link as. Here I grab the mmdet Mask2Former instance segmentation model as an example.
![image](https://user-images.githubusercontent.com/14964580/201261459-5a79f99a-2c8b-4728-82d0-345a5a89f0cc.png)

The official MMDetection models tend to have additional config files required, listed at the top of the config file.
![image](https://user-images.githubusercontent.com/14964580/201261826-ed75838f-3fa5-43e0-b570-d9856226db71.png)
You will need to download those from the repo as well, scroll up from the model downloads to view the root path of these configs. Sometimes those config files will list even further config files you need from the mmdet repo.
![image](https://user-images.githubusercontent.com/14964580/201262037-09a6bdbd-4ad1-4953-9443-c6179d616f13.png)
Download any additional configs from the relative path in the repo. Modify the relative paths in a text editor so that they are just pointing to the current directory so you can just keep them in the models folder with your model.
![image](https://user-images.githubusercontent.com/14964580/201262536-9eb15133-4a33-4548-9c51-220d812635a5.png)
After collecting all the dependency configs the model directory will look something like this:
![image](https://user-images.githubusercontent.com/14964580/201264181-c7e628cb-1f56-4e63-8c39-d09371b69fcf.png)
Restart the webui for the model to appear in your list:
![image](https://user-images.githubusercontent.com/14964580/201265898-324bae3e-f513-4648-9bf1-64970ae6724a.png)

**Comment by StableInquest** [comment]
Thanks so much, that's really helpful!

**Comment by soysanti** [comment]
ohh this looks great, would there be a way to subtract the head (the B) and not just the face? Thank you!
