### ISSUE TITLE
Possible to run script only once for batch process?

### ISSUE THREAD

**Issue by henryvii99** [dustysys/ddetailer#6]
From my very limited understand about programming,
it seems that when I am running the script,
it outlines the person, then inpaints with whatever prompts I wrote in img2img.

However when I am running batch process (e.g. set batch count to 12),
it runs every time the image generates.
But since I am using the same parent image for edit, 
is it possible to just run the script once to outline, then generate 12 images from it?

Many thanks for your help!

**Comment by dustysys** [comment]
I've considered this optimization but didn't want to add it yet because it optimizes one mode (img2img) but makes changing all the other modes (txt2img, img2img w/ model B preprocessing, future planned img2img post-processing) more difficult, programming-wise. For now, you may find it helpful to turn on mask saving in the settings. The generated mask images can be used with the upload mask selection in normal img2img inpainting mode to reroll as much as you like without any script or object detection overhead.

**Comment by trihardseven** [comment]
> I've considered this optimization but didn't want to add it yet because it optimizes one mode (img2img) but makes changing all the other modes (txt2img, img2img w/ model B preprocessing, future planned img2img post-processing) more difficult, programming-wise. For now, you may find it helpful to turn on mask saving in the settings. The generated mask images can be used with the upload mask selection in normal img2img inpainting mode to reroll as much as you like without any script or object detection overhead.

How do I turn on mask saving? I can't find this setting
